--- 
- :id: Default
  :name: Default
  :model: source
  :labels: 
  - Labels
  :rules: 
  - CataloguingRules
  :options: 
  - FormOptions
  :layout: 
  - LayoutDefault
  :filter: 
    default: true
    
###
- :id: Print
  :name: Print
  :model: source
  :labels: 
  - Labels
  :rules: 
  - CataloguingRules
  :options: 
  - FormOptions
  :layout:
  - LayoutPrint
  :filter: 
    leader: !ruby/regexp /.....(ccd|ccm|ncm).............../
    tag: "100"
    
###
- :id: Show
  :name: Show
  :model: source
  :labels: 
  - Labels
  :rules: 
  - CataloguingRules
  :options: 
  - FormOptions
  :layout: 
  - LayoutShow
  :filter: 
    show_all: false
    show: true
    
###
- :id: Holding
  :name: holding
  :model: source
  :labels: 
  - Labels
  :rules: 
  - CataloguingRules
  :options: 
  - FormOptions
  :layout: 
  - LayoutHolding
  :filter: 
    holding: true

# Configuration for person
- :id: DefaultPerson
  :name: Default Person
  :model: person
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - PersonBasicFormOptions
  :layout: 
  - PersonLayoutDefault
  :filter: 
    default: true
- :id: ShowPerson
  :name: Show Person
  :model: person
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - PersonBasicFormOptions
  :layout: 
  - PersonLayoutShow
  :filter:
    show_all: false
    show: true

