--- 
- :id: Default
  :name: Default
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutDefault
  :filter: 
    default: true
- :id: Print
  :name: Print
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPrint
  - LayoutContents
  :filter: 
    leader: !ruby/regexp /.....ncm.............../
- :id: Show
  :name: Show
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutShow
  - LayoutContents
  :filter: 
    show_all: false
    show: true
