
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: library
:tags:
  "000": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008": 
    :master: ""
    :indicator: ""
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "043": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "*"
    - - b
      - :occurances: "*"
    - - c
      - :occurances: "*"
  "110": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
    - - c
      - :occurances: "?"
    - - g
      - :occurances: "?"
  "410": 
    :master: a
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
  "622": 
    :master: e
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - e
      - :occurances: "?"
    - - u
      - :occurances: "?"
