
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: person
:tags:
  "000": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "007": 
    :master: ""
    :indicator: "" 
    :occurances: "*"
    :fields:
    - - ""
      - :no_browse: true
  "008": 
    :master: ""
    :indicator: ""
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "035": 
    :master: a
    :indicator: "##"
    :occurances: "*"    
    :fields: 
    - - a
      - :occurances: "?"
  "039": 
    :master: a
    :indicator: "##"
    :occurances: "*"    
    :fields: 
    - - a
      - :occurances: "?"
  "040": 
    :master: a
    :indicator: "##"
    :occurances: "1"
    :fields: 
    - - a
      - :occurances: "1"
    - - b
      - :occurances: "1"
    - - c
      - :occurances: "1"
    - - d
      - :occurances: "?"

  "043": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "*"
    - - b
      - :occurances: "*"
    - - c
      - :occurances: "*"
  "100": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
    - - d
      - :occurances: "?"
        :browse_inline: true
  "210": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
  "240": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
  "400": 
    :master: a
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - d
      - :occurances: "?"
# This is a linked field
  "509": 
    :master: "0"
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - "0"
      - :occurances: "?"
    - - "9"
      - :occurances: "?"
  "549": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
  "559": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
  "569": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"    
  "670": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - b
      - :occurances: "?"
    - - u
      - :occurances: "?"
  "678": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - b
      - :occurances: "?"
    - - u
      - :occurances: "?"
  "680": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - i
      - :occurances: "?"
    - - "5"
      - :occurances: "?"
  "684": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - j
      - :occurances: "?"
  "856": 
    :master: u
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - u
      - :occurances: "?"
    - - y
      - :occurances: "?"
