
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: catalogue
:tags:
  "000": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008": 
    :master: ""
    :indicator: ""
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "100": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
    - - "0"
      - :occurances: "?"
        :browse_inline: true
  "210": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
  "240": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
  "260": 
    :master: a
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - c
      - :occurances: "?"
  "700": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - "0"
      - :occurances: "?"
    - - "4"
      - :occurances: "?"
  "760": 
    :master: g
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - g
      - :occurances: "?"
    - - t
      - :occurances: "?"
