
:version:
  :name: tag_config
  :current: 2.0
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# NOTES FOR "tags" SECTION:
#
# The ":dependency:" field indicates a subtags reliance and function according to its parent.  Values are:
# false (no parent for this subtag.  Used for "a" or "" subtags or other subtags that are independant of other subtags)
# true  (must be in addition to parent subtag, cannot exist without it)
#
# Subtag ":occurrences:" fields are always within context of thier parent subtag.  In the case of parent sutags ("a", "" (blank)
# and some "w" tags) this defines the repetition attributes for the whole tag
#
# 0 (none. used only to keep tag/subtag configurations that are unused and therefore discarded on import)
# ? (none or one. this subtag need not be present, but at most only one occurance may exist)
# 1 (one occurance must exist. no more than one is allowed)
# + (one or more must exist.  at least one occurance must be present, more occurrences are allowed)
# * (none or more. none, one or many may exist)
#
# >where a tag or subtag is repeatable, there shouldn't be an upper limit on number of repeats allowed,
# >so I've amended all the values in the max_occur fields to "0".
# max_occur has now been removed entirely
#
# *DEPRECATED AND REMOVED* The "max_occur:" field is used in conjunction with the '+' or '*' ":occurrences:"
# field values to limit the number of occurrences to the specified maximum value.  A value of 0 inidicates
# and unlimited number of occurrences.  Only set this value to a positive number if it is absolutely
# necessary to set an upper limit on the number of occurrences of this subtag.
#
# >ST NOTE: TAGS 000 to 008
# >These are different from all the later tags in that they don't have any subtags (not even "a").
# >So should the master for each be changed to "" instead of a?
# This has now been corrected
#
# The ":export_as:" field specifies the mandatory value for a subtag on an export.  The subtag is only
# exported if both ":occurrences:" is set to "0" and this value is present.  This applies only to dependent
# subtags (i.e. not "a" subtags).
#
# "index" fields specify which marc fields are included in the fulltext ferret index when a record is
# inserted or updated in the masters table. See search_config.X.X.yml for more details on search functionality
# and the fulltext index.

:model: holding
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "852":
    :master: "0"
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "1"
        :foreign_class: ^0
        :foreign_field: siglum
        :browse_helper: application_helper_link_to_library
    - - b
      - :occurrences: "?"
    - - d
      - :occurrences: "*"
    - - e
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
    - - p
      - :occurrences: "?"
    - - q
      - :occurrences: "?"
    - - u
      - :occurrences: "*"
    - - x
      - :occurrences: "*"
        :no_browse: true
    - - z
      - :occurrences: "*"