
:version:
  :name: tag_config
  :current: 2.0
  :authors: ["Rodolfo Zitellini"]

:model: holding
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "852":
    :master: "0"
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "1"
        :foreign_class: ^0
        :foreign_field: siglum
        :browse_helper: application_helper_link_to_library
    - - b
      - :occurrences: "?"
    - - d
      - :occurrences: "*"
    - - e
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
    - - p
      - :occurrences: "?"
    - - q
      - :occurrences: "?"
    - - u
      - :occurrences: "*"
    - - x
      - :occurrences: "*"
        :no_browse: true
    - - z
      - :occurrences: "*"