
:version:
  :name: tag_config
  :current: 2.0
  :authors: ["Rodolfo Zitellini"]

:model: holding
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "506":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "541":
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
    - - c
      - :occurrences: "?"
    - - d
      - :occurrences: "?"
    - - e
      - :occurrences: "?"
  "561":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "591":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "852":
    :master: "x"
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - "x"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "1"
        :foreign_class: ^x
        :foreign_field: siglum
        :browse_helper: application_helper_link_to_library
    - - b
      - :occurrences: "?"
    - - d
      - :occurrences: "*"
    - - e
      - :occurrences: "?"
        :foreign_class: ^x
        :foreign_field: name
        :disable_create_lookup: true
    - - p
      - :occurrences: "?"
    - - z
      - :occurrences: "*"
  "856":
    :master: u
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - u
      - :occurrences: "*"
        :browse_helper: application_helper_link_http
    - - x
      - :occurrences: "?"
    - - z
      - :occurrences: "*"
    - - "8"
      - :occurrences: "?"
        :no_browse: true