
# Version 2 - For SOLR and Muscat 3

config:
    :version: 2.0
    :model: source

fields:  
  "001":
  "008":
      :index_helper: :extract_search_fields_from_008
  "028a":
  "028b":
  "031d":
  "031e":
  "031m":
  "031p":
      :store: :yes
#      :ceded_index_helper: :create_incipit_ch
  "031q":
  "031t":
  "033a":
  "035a":
  "041a":
  "041e":
  "041h":
  "100a":
  "100d":
  "110a":
  "110b":
  "130a":
  "130k":
  "130m":
  "130n":
      :store: :yes
  "130o":
  "130p":
  "130r":
  "240a":
  "240k":
  "240m":
  "240n":
      :store: :yes
  "240o":
  "240p":
  "240r":
  "245a":
  "245b":
  "245c":
  "246a":
  "246i":
  "254a":
  "260a":
  "260b":
  "260c":
  "260e":
  "260f":
  "270a":
  "300a":
  "300b":
  "300c":
  "340c":
  "340d":
  "351a":
      :no_index_value: xxxx
  "500a":
      :no_index_value: xxxx
  "5005":
  "505a":
  "506a":
  "508a":
  "510a":
  "510c":
  "511a":
  "518a":
  "520a":
  "525a":
  "533a":
  "541a":
  "541c":
  "541d":
  "545a":
  "546a":
  "555a":
  "561a":
      :no_index_value: xxxx
  "5615":
  "562a":
  "5625":
  "563a":
  "5635":
  "590a":
  "590b":
  "591a":
  "592a":
  "593a":
  "594a":
  "594b":
  "594c":
  "594d":
  "594e":
  "594f":
  "594g":
  "594h":
  "594i":
  "594k":
  "594l":
  "594m":
  "594n":
  "595a":
  "596a":
  "597a":
  "598a":
  "599a":
  "600a":
      :store: :yes
  "650a":
  "651a":
  "653a":
  "657a":
  "690a":
  "691a":
  "700a":
  "700d":
  "700e":
  "700t":
  "7004":
  "7005":
  "710a":
  "710b":
  "710k":
  "710e":
  "7104":
  "7105":
  "730a":
  "730k":
  "730m":
  "730n":
      :store: :yes
  "730o":
  "730p":
  "730r":
  "740a":
  "752a":
  "752d":
  "772w":
  "773w":
  "786a":
  "786d":
  "786i":
  "786o":
  "786t":
  "787a":
  "787n":
  "787w":
  "787w":
  "787w":
  "787w":
  "787w":
  "787w":
  "852a":
  "852b":
  "852d":
  "852e":
  "852p":
      :store: :yes
  "852q":
  "852z":
  "856u":
