
# Version 2 - For SOLR and Muscat 3

config:
    :version: 2.0
    :model: person

fields:  
    "001":
    "008":
    "035a":
    "039a":
    "040a":
    "040b":
    "040c":
    "040d":
    "043a": 
    "043b":
    "043c":
    "100a":
    "100d":
    "400a":
    "400d": 
    "5099":
    "549a": 
    "559a": 
    "569a": 
    "670a":
    "670b":
    "670u":
    "678a": 
    "678b":
    "678u":	
    "680a": 
    "680i":
    "6805":	
    "684a": 
    "674j":