--- !map:Settings 
group_order: 
- control
- codes
- main
- notes
groups: 
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - 008
  notes: 
    all_tags: 
    - "509"
    - "549"
    - "559"
    - "569"
    - "856"
  main: 
    all_tags: 
    - "110"
    - "410"
  codes: 
    all_tags: 
    - "039"
    - "040"
    - "043"

