server:
  version: 1.1
  port: 80
  database: 
    title: RISM Répértoire des sources musicales Muscat 
    description: SRU/SRW Gateway based on Solr. Records in UTF-8 encoding. Contains sources, people, institutions and catalogues.
sets:
  cql: info:srw/cql-context-set/1/cql-v1.1
  rec: info:srw/cql-context-set/2/rec-1.1
  dc: info:srw/cql-context-set/1/dc-v1.1
  bath: http://zing.z3950.org/cql/bath/2.0/
index:
  dc.id:
    solr: "001"
    type: string
  dc.title:
    solr: 
      - 240a
      - 245a
    type: string
  dc.subject:
    solr: 650a
    type: string
  dc.creator:
    solr: 100a
    type: string
  dc.author:
    solr: 100a
    type: string
  dc.publisher:
    solr: 260b
    type: string
  dc.description:
    solr: 500a
    type: string
  dc.date:
    solr: 260c
    type: string
  bath.possessingInstitution:
    solr: 852a
    type: string
  bath.name:
    solr: 
      - 100a
      - 700a
    type: string
  bath.personalName:
    solr: 100a
    type: string
  bath.corporateName:
    solr: 110a
    type: string
  bath.uniformTitle:
    solr: 240a
    type: string
  bath.notes:
    solr: 500a
    type: string
  bath.topicalSubject:
    solr: 650a
    type: string
  rism.profession:
    solr: 550a
    type: string
  rism.gender:
    solr: 375a
    type: string
  rism.siglum:
    solr: 852a
    type: string
  rism.country:
    solr: 043a
    type: string
  rism.watermark:
    solr: 592a
    type: string
  rism.composer:
    solr: 100a
    type: string
  rism.relatedPerson:
    solr: 700a
    type: string
  rism.libarySiglum:
    solr: 110g
    type: string
  rism.changed:
    solr: updated_at
    type: date
  rism.created:
    solr: created_at
    type: dateg


  #bath.genreForm:
    #title: genreForm
    #solr: 001
  #bath.keyTitle:
    #title: id
    #solr: 001
  #rism.adatum:
    #title: adatum
    #solr: 001
  #rism.provider:
    #title: provider
    #solr: 001
  #rism.place:
    #title: place
    #solr: 001
  #dc.editor:
    #title: id
    #solr: 001
  #dc.image:
    #title: image
    #solr: 001
  #dc.year:
    # title: year
    # solr: 001
  #dc.resourceType:
    #title: id
    #solr: 
  #dc.format:
    #title: id
    #solr: 001
  #dc.resourceIdentifier:
    #title: id
    #solr: 001
  #dc.source:
    #title: id
    #solr: 001
  #dc.language:
    #title: id
    #solr: 001
  #dc.relation:
    #title: id
    #solr: 001
  #dc.coverage:
    #title: id
    #solr: 001
  #dc.rights:
    #title: id
    #solr: 
  #bath.conferenceName:
    #title: conferenceName
    #solr: 001
  #bath.isbn:
    #title: isbn
    #solr: 001
  #bath.issn:
    #title: issn
    #solr: 001
  #bath.geographicName:
    #title: geographicName
    #solr: 001
