--- !map:Settings 
group_order: 
- main
- administration
groups: 
  administration: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
  main: 
    all_tags: 
    - "110"
    - "410"
    - "622"
    - "680"
