--- !map:Settings 
groups: 
  physical_description: 
    all_tags: 
    - 028
    - "563"
    - "525"
    - "500"
  material_description: 
    all_tags: 
    - "593"
    - "340"
    - "300"
    - "260"
    - "592"
    subfield_grouping: 8
