--- !map:Settings 
group_order: 
- main_person
- notes
- subject
- codes
groups: 
  notes: 
    all_tags: 
    - "509"
    - "549"
    - "559"
    - "569"
  subject: 
    all_tags: 
    - "670"
    - "678"
    - "680"
    - "684"
  main_person: 
    all_tags: 
    - "100"
    - "400"
  codes: 
    all_tags: 
    - "035"
    - "039"
    - "040"
    - "043"