--- !map:Settings 
group_order: 
- main
groups: 
  administration: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
  main: 
    all_tags: 
    - "100"
    - "210"
    - "240"
    - "260"
    - "760"
