--- !map:Settings 
doc_abbreviations: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: "Abk\xC3\xBCrzungen"
    en: Abbreviations
doc_aid: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Arbeitshilfen
    en: Aide
doc_cataloguing_collections: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Erfassung von Sammlungen
    en: Cataloging collection and convoluta
doc_functions: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: "Grund\xC3\xA4tzliche Funktionen"
    en: Basic functions
doc_introduction: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Einleitung
    en: Introduction
doc_masks: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Masken
    en: Cataloging forms
doc_tag_index: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: MARC Tag Index
    en: MARC tag index
doc_templates: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Templates
    en: Templates
"000": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Leader
    fr: Guide
    de: Leader
    en: Leader
"001": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Numero documento RISM
    fr: No. RISM
    de: RISM Dokumentnummer
    en: RISM ID No.
"003": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Identificatore del numero di controllo
    fr: "Identit\xC3\xA9 du num\xC3\xA9ro de contr\xC3\xB4le"
    de: Kontrollnummer-Bezeichnung
    en: Control number identifier
"005": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Data e ora dell'ultima transazione
    fr: "Date/heure de la derni\xC3\xA8re transaction"
    de: Datum und Zeit der letzten Transaktion
    en: Date and time of last transaction
"043": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Country code
    fr: Country code
    de: Länder-Code
    en: County code
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    c: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Country code
        fr: Country code
        de: Länder-Code  
        en: Country code
"100": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Nome di ente
    fr: "Nom de la collectivit\xC3\xA9"
    de: "K\xC3\xB6rperschaftsname"
    en: Authors
  accepts: 
  - "710"
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    a: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Nome di ente
        fr: "Nom de la collectivit\xC3\xA9"
        de: "K\xC3\xB6rperschaftsname"
        en: Author
    b: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Ente subordinato
        fr: "Collectivit\xC3\xA9 subordonn\xC3\xA9e"
        de: "Untergeordnete K\xC3\xB6rperschaft"
        en: Subordinate unit
    c: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Place
        fr: Place 
        de: Ort
        en: Place
    g: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Ente subordinato
        fr: "Siglum"
        de: "Sigel"
        en: Siglum
"210": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Name variants
    fr: Name variants
    de: Namensvarianten
    en: Short title
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    a: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Name variants
        fr: Name variants
        de: Namensvarianten  
        en: Short title
"240": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Contact 
    fr: Contact
    de: Kontakt
    en: Title
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    e: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Address
        fr: Address
        de: Adresse
        en: Address 
    u: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: URL
        fr: URL
        de: URL
        en: URL

main: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Registrazioni principali
    fr: "Entr\xC3\xA9es principales"
    de: Haupteintragungen
    en: Main entry fields
codes: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Numeri e codici
    fr: "Num\xC3\xA9ros et codes"
    de: Nummern und Codes
    en: Numbers and code fields
control: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    fr: "Champs de contr\xC3\xB4le"
    de: Kontrollfelder
    ot: Campi di controllo
    en: Control Fields
notes: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Note
    fr: Notes
    de: Fussnoten
    en: Note fields
other: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Varia
    fr: Divers
    de: Verschiedenes
    en: Miscellaneous

