--- !map:Settings 
group_order: 
- main
- codes
- control
- notes
groups: 
  main: 
    all_tags: 
    - "240"
    - "260"            
    - "100"
    - "700"
    - "710"
    - "760"
    all_tag_templates:
      "700": marc_show/show_person
      "710": marc_show/show_institution
      "760": marc_show/show_catalogue
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - 008
  notes: 
    all_tags: 
    - "760"
  codes: 
    all_tags: 
    - "210"
