--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"041": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
    columns: 2
  tag_params:
    codes:
      - "cat"
      - "cze"
      - "dan"
      - "dut"
      - "eng"
      - "fre"
      - "ger"
      - "grc"
      - "gre" 
      - "gsw"
      - "heb"
      - "hrv"
      - "hun"
      - "ita"
      - "kor"
      - "lat"
      - "pol"
      - "por"
      - "rus"
      - "slo"
      - "slv"
      - "spa"
      - "srp"
      - "swe"
      - "zxx"
"100": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
"210": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"240": 
  layout: 
    fields: 
    - - a
    - - g
      - cols: 1
        values:
        # http://www.loc.gov/standards/valuelist/marcgt.html
        - "abstract or summary"
        - "article"
        - "autobiography" 
        - "bibliography"
        - "biography"
        - "book"
        - "catalog"
        - "conference publication"
        - "database"
        - "dictionary"
        - "directory"
        - "discography"
        - "edition"
        - "encyclopedia"
        - "essay"
        - "festschrift"
        - "fiction"
        - "font"
        - "government publication"
        - "graphic"
        - "handbook"
        - "history"
        - "hymnal"
        - "index"
        - "instruction"
        - "interview"
        - "issue"
        - "journal"
        - "letter"
        - "loose-leaf"
        - "memoir"
        - "microscope slide"
        - "model"
        - "multivolume monograph"
        - "newspaper"
        - "numeric data"
        - "offprint"
        - "online system or service"
        - "other"
        - "periodical"
        - "programmed text"
        - "realia"
        - "rehearsal"
        - "reporting" 
        - "review"
        - "script"
        - "series"
        - "slide"
        - "sound"
        - "speech"
        - "standard or specification"
        - "survey of literature"
        - "thematic catalog"
        - "thesis"
        - "transparency"
        - "treaty"
        - "web site"
        - "work catalog"
        - "yearbook"
        editor_partial: subfield_select
    - - h
      - cols: 1
        values:
        - "book"
        - "electronic resource"
        - "individual item"
        - "item"
        - "journal"
        - "periodical"
        - "series"
        editor_partial: subfield_select
"260": 
  layout: 
    fields: 
    - - a
      - cols: 4
    - - b
      - cols: 4
    - - c
      - cols: 4
    columns: 4
"264": 
  layout: 
    fields: 
    - - c
      - cols: 4
"300": 
  layout: 
    fields: 
    - - a
      - cols: 4
"337": 
  layout: 
    fields: 
    - - a
      - cols: 4
        values:
        - "Printed Book"
        - "Manuscript"
        - "Electronic resource"
        - "Sheet music"
        - "Audiovisual media"
        - "CD-ROM"
        - "Combination"
        - "Other"
        default: "Printed Book"
        editor_partial: subfield_select
"500": 
  layout: 
    fields: 
    - - a
      - cols: 4
"520": 
  layout: 
    fields: 
    - - a
      - cols: 4
"599": 
  layout: 
    fields: 
    - - a
      - cols: 4
"650":
  allow_new: true
  new_window: standard_terms
  layout: 
    fields: 
    - - a
      - type: standard_term
        editor_partial: subfield_secondary
"651": 
  allow_new: true
  new_window: places
  layout: 
    fields: 
    - - a
      - type: place
        editor_partial: subfield_secondary
"700":
  allow_new: true
  new_window: people
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
    - - "4"
      - editor_partial: subfield_relator_codes_700
  tag_list_additional_data: tag_list_additional_data_relator_codes
  tag_params: 
    groups: 
      01_codes_artistic: 
      - cmp
      - com
      - arr
      - aut
      - clb
      - lyr
      - ccp
      - lbt
      - trl
      02_codes_performing: 
      - prf
      - voc
      - itr
      - dnc
      - cnd
      - chr
      - art
      - cst
      - prd
      - cns
      04_codes_other: 
      - fmo
      - dnr
      - dte
      - pat
      - otm
      - bsl
      - asn
      - dub
      03_codes_technical: 
      - scr
      - ltg
      - egr
      - ill
      - prt
      - pbl
      - edt
      - bnd
"710":
  allow_new: true
  new_window: institutions
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
    - - b
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
  tag_params: 
    codes: 
    - fmo
    - dnr
    - dte
    - prf
    - otm
    - ppm
    - prt
    - pbl
    - edt
    - bsl
    - asn
    - dub
"760": 
  allow_new: true
  new_window: catalogues
  layout: 
    fields: 
    - - t
      - type: catalogue
        editor_partial: subfield_secondary
    - - g     
"785": 
  allow_new: true
  new_window: catalogues
  layout: 
    fields: 
    - - a
      - type: catalogue
        editor_partial: subfield_secondary
"856": 
  layout: 
    fields: 
    - - u
    - - z
