--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
008: 
  tag: tag_no_subfield
  tag_params: 
    maskedinput: 
      definitions: "['~']='[|0-9]'"
      mask: 999999a~~~~~~~~||||||||||||||||||||aaa|d
  tag_header: none
"100": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
    - - j
      - value: Attributed to
        editor_partial: subfield_checkbox
"210": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"240": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"260": 
  layout: 
    fields: 
    - - a
      - cols: 4
    - - c
      - cols: 4
    columns: 4
"700": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
    - - j
      - value: Attributed to
        editor_partial: subfield_checkbox
"710": 
  allow_new: true
  new_window: institutions
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
"760": 
  allow_new: true
  new_window: catalogues
  layout: 
    fields: 
    - - t
      - type: catalogue
        editor_partial: subfield_secondary
    - - g      
