--- !map:Settings 
group_order: 
- main
- codes
- control
- notes
groups: 
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
  notes: 
    all_tags: 
    - "260"
    - "700"
    - "760"
  main: 
    all_tags: 
    - "100"
    - "240"
    - "508"
  codes: 
    all_tags: 
    - "041"
    - "650"
    - "210"
