--- !map:Settings 
group_order: 
- control
- codes
- main
- notes
groups: 
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - 008
  notes: 
    all_tags: 
    - "622"
  main: 
    all_tags: 
    - "110"
    - "410"
  codes: 
    all_tags: 
    - "043"
