--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
008: 
  tag: tag_no_subfield
  tag_params: 
    maskedinput: 
      definitions: "['~']='[|0-9]'"
      mask: 999999a~~~~~~~~||||||||||||||||||||aaa|d
  tag_header: none
"043": 
  layout: 
    fields: 
    - - c
      - cols: 2
    columns: 4
"110": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - c
      - cols: 2
    - - g
      - cols: 2
    columns: 4
"410": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"580": 
  layout: 
    fields: 
    - - "x"
      - type: institution
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4

"622": 
  layout: 
    fields: 
    - - e
      - cols: 2
    - - u
      - cols: 2
    columns: 4
"670": 
  layout: 
    fields: 
    - - "a"
      - type: catalogue
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4
"700":
  allow_new: true
  new_window: people
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
    - - "4"
      - editor_partial: subfield_relator_codes_700
  layout_new:
    fields: 
    - - a
    - - d
    - - "4"
      - editor_partial: subfield_relator_codes_700
  tag_list_additional_data: tag_list_additional_data_relator_codes
  tag_params: 
    groups: 
      01_codes_artistic: 
      - cmp
      - com
      - arr
      - aut
      - clb
      - lyr
      - ccp
      - lbt
      - trl
      02_codes_performing: 
      - prf
      - voc
      - itr
      - dnc
      - cnd
      - chr
      - art
      - cst
      - prd
      - cns
      04_codes_other: 
      - fmo
      - dnr
      - dte
      - pat
      - otm
      - bsl
      - asn
      - dub
      03_codes_technical: 
      - scr
      - ltg
      - egr
      - ill
      - prt
      - pbl
      - edt
      - bnd

"710": 
  layout: 
    fields: 
    - - "a"
      - type: institution
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4


