--- !map:Settings 
group_order: 
- group_identification
- group_location
- group_physical
- group_identification_notes
- group_references
- group_linking
- group_works
- group_administration
groups: 
  group_linking: 
    all_tag_templates: 
      "775": show_775_link
    all_tags: 
    - "775"
  group_administration: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - 008
    - "040"
    - "599"
    admin_only: true
  group_works: 
    all_tag_templates: 
      "600": show_work
    all_tags: 
    - "600"
  group_location: 
    all_tag_templates: 
      "852": show_libraries
    all_tags: 
    - "852"
  group_physical: 
    all_tag_templates: 
      "300": show_phys
    all_tags: 
    - "300"
    - "340"
  group_identification: 
    all_tag_templates: 
      "260": show_subfield_concat
      "100": show_person
      "510": show_rism
    all_tags: 
    - "100"
    - "240"
    - "245"
    - "260"
    - "510"
    - "500"
    - "033"
    - "035"
  group_identification_notes: 
    all_tags: 
    - "508"
    - "505"
  group_references: 
    all_tag_templates: 
      "710": show_institution
      "700": show_person
    all_tags: 
    - "700"
    - "710"
