--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"008": 
  tag: tag_no_subfield
  tag_params: 
    maskedinput: 
      definitions: "['~']='[|0-9]'"
      mask: 999999a~~~~~~~~||||||||||||||||||||aaa|d
  tag_header: none
"024": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - "2"
      - values: 
        - "BNE"
        - "BNF"
        - "DNB"
        - "ICCU"
        - "ISNI"
        - "LC"
        - "NLP"
        - "NKC"
        - "SWNL"
        - "VIAF"
        - "WKP"
        editor_partial: subfield_select
      - cols: 2
    columns: 4

"040": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - c
      - cols: 2
    - - d
      - cols: 2
    - - b
      - cols: 2
    columns: 4
"042": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"043": 
  layout: 
    fields: 
    - - a
      - cols: 4
    - - b
      - cols: 2
    - - c
      - cols: 2
    columns: 4
"100": 
  layout: 
    fields: 
    - - a
      - cols: 2
        trigger:
        - save:
          - Source
    - - c
      - cols: 2
    - - d
      - cols: 2
    - - w
      - cols: 2
    - - y
      - cols: 2
    columns: 4
"374": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"375": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_gender_codes_375
    columns: 2
  tag_params:
    codes:
      - male
      - female
      - "unknown"
"400": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - d
      - cols: 2
    - - j
      - cols: 2
    columns: 4
"500": 
  layout: 
    fields: 
    - - "a"
      - type: person
        editor_partial: subfield_secondary
      - cols: 4
    - - "i"
      - cols: 2
    columns: 4
"510": 
  layout: 
    fields: 
    - - "a"
      - type: institution
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4
"549": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"551": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - i
      - cols: 2
    columns: 2
"599": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - b
      - cols: 2
    columns: 4
"667": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"670": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - b
      - cols: 2
    columns: 4
"678": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - b
      - cols: 2
    - - u
      - cols: 4
    columns: 4
"680": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - i
      - cols: 2
    - - "5"
      - cols: 4
    columns: 4
"856": 
  layout: 
    fields: 
    - - u
      - cols: 2
    - - y
      - cols: 2
    columns: 4
