--- !map:Settings 
group_order: 
- main_person
- administration
groups: 
  administration: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - "040"
  other: 
    all_tags: 
    - "509"
    - "549"
    - "559"
    - "569"
    - "678"
    - "684"
  main_person: 
    all_tags: 
    - "100"
    - "400"
    - "370"
    - "375"
    - "670"
    - "680"
  codes: 
    all_tags: 
    - "035"
    - "039"
    - "040"
    - "043"

