--- !map:Settings 
group_order: 
- control
- codes
- main_person
- notes
- subject
groups: 
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - "008"
  notes: 
    all_tags: 
    - "510"
    - "551"
    - "856"
    - "667"
  subject: 
    all_tags: 
    - "670"
    - "678"
    - "680"
    - "374"
    - "500"
  main_person: 
    all_tags: 
    - "100"
    - "400"
  codes: 
    all_tags: 
    - "024"
    - "375"
    - "042"
    - "040"
    - "043"

