--- !map:Settings 
group_order: 
- main_person
- codes
- notes
- places
- variants
groups:   
  main_person: 
    all_tags: 
    - "100"
    - "042"
    - "375"   
    - "374" 
    all_tag_templates:
      "375": marc_show/show_gender  
      "374": marc_show/show_inline

  notes: 
    all_tags: 
    - "500"
    - "599"
    - "667"
    - "856"
    all_tag_templates:
      "500": people/show_related_person
      "374": marc_show/show_inline
      "856": people/show_link
  places: 
    all_tags: 
    - "510"
    - "043"
    - "670"
    - "678"
    - "680"
    - "551"
    all_tag_templates:
      "043": marc_show/show_subfield_concat
      #"569": people/show_indicator
  codes: 
    all_tags: 
    - "035"
    all_tag_templates:
      "035": marc_show/show_dnb_link
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - "008"
  variants:
    all_tags:
    - "400"
    all_tag_templates:
      "400": people/show_indicator
