--- !map:Settings 
group_order: 
- main_person
- codes
- notes
- subject
- variants
groups:   
  main_person: 
    all_tags: 
    - "100"
    - "042"
    - "039"    
    all_tag_templates:
      "039": marc_show/show_gender  

  notes: 
    all_tags: 
    - "509"
    - "549"
    - "559"
    - "599"
    - "667"
    - "670"
    - "856"
  subject: 
    all_tags: 
    - "510"
    - "043"
    - "569"
    - "670"
    - "678"
    - "680"
    - "684"
  codes: 
    all_tags: 
    - "035"
    all_tag_templates:
      "035": marc_show/show_dnb_link
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - "008"
  variants:
    all_tags:
    - "400"
