--- !map:Settings 
group_order: 
- edit_library
- edit_names
- edit_content
- edit_material
- edit_incipits
- edit_references
- edit_administration

group_exclude:
  collection:
  - edit_incipits
  manuscript_libretto:
  - edit_incipits
  print_libretto:
  - edit_incipits
  theoretica:
  - edit_incipits
  convolutum:
  - edit_incipits
  
tag_exclude:
  collection:
  - '041'
  - '511'
  - '546'
  - '650'
  - '653'
  - '651'
  - '657'
  - '740'
  - '787'
  manuscript:
  - '772'
  print:
  - '772'
  manuscript_libretto:
  - '590'
  - '594'
  - '596'
  - '598'
  - '772'
  - '787'
  print_libretto:
  - '590'
  - '594'
  - '596'
  - '598'
  - '772'
  - '787'
  theoretica:
  - '511'
  - '590'
  - '594'
  - '596'
  - '598'
  - '651'
  - '653'
  - '657'
  - '690'
  - '772'
  - '787'
  convolutum:
  - '028'
  - '041'
  - '100'
  - '240'
  - '260'
  - '300'
  - '340'
  - '511'
  - '546'
  - '590'
  - '592'
  - '593'
  - '650'
  - '653'
  - '651'
  - '657'
  - '730'
  - '740'
  - '773'
  - '787'

groups:
  edit_library:
    all_tags:
    - '852'
    - '591'
    - '035'
    - '506'
    - '561'
    - '541'
    - '773'
    - '787'
    - '772'
  edit_names:
    all_tags:
    - '100'
    - '700'
    - '710'
    ungrouped_tags:
     "700": 8
     "710": 8
  edit_content:
    all_tags:
    - '245'
    - '246'
    - '240'
    - '690'
    - '383'
    - '730'
    - '650'
    - '520'
    - '594'
    - '598'
    - '653'
    - '740'
    - '041'
    - '546'
  edit_material:
    all_tags:
    - '593'
    - '260'
    - '033'
    - '518'
    - '300'
    - '590'
    - '340'
    - '028'
    - '592'
    - '700'
    - '710'
    - '500'
    - '856'
    subfield_grouping: 8
  edit_incipits:
    all_tags:
    - '031'
    template: show_incipit
  edit_references:
    all_tags:
    - '500'
    - '525'
    - '691'
    - '596'
    - '657'
    - '651'
    - '511'
    - '033'
    - '518'
    - '856'
    ungrouped_tags:
     "033": 8
     "500": 8
     "518": 8
     "856": 8
  edit_administration:
    all_tags:
    - '001'
    - '040'
    - '599'
