--- !map:Settings
"031": 
  tags:
    a: required
    b: required
    c: required
    e:
      retuired_if:
        "031": "m"
    n:
      retuired_if:
        "031": "p"
    o:
      retuired_if:
        "031": "p"
    r:
      retuired_if:
        "031": "p"
"041": 
  tags:
    a:
      retuired_if:
        "031": "t"
"100": 
  tags:
    "0": required
"240": 
  tags:
    m: required
"245": 
  tags:
    a: required
"260": 
  tags:
    c: required
"300": 
  tags:
    a: required
"593": 
  tags:
    a: required