--- !map:Settings 
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"028": 
  layout: 
    fields: 
    - - a
"031": 
  layout: 
    fields:
    - - u
      - hidden: true
    - - a
#      - validate: 
#        - msg: the format must be numeric
#          value: "'^[0-9][0-9]*$'"
#          rule: regex
#        - msg: the field is required
#          value: true
#          rule: required
    - - b
#      - validate: 
#        - msg: the format must be numeric
#          value: "'^[0-9][0-9]*$'"
#          rule: regex
#        - msg: the field is required
#          value: true
#          rule: required
    - - c
#      - validate: 
#        - msg: the format must be numeric
#          value: "'^[0-9][0-9]*$'"
#          rule: regex
#        - msg: the field is required
#          value: true
#          rule: required
    - - d
    - - m
    - - e
    - - t
      - growfield: true
    - - r
    - - o
    - - g
      - values: 
        - "G-1"
        - "G-2"
        - "g-2"
        - "C-1"
        - "C-2"
        - "C-3"
        - "C-4"
        - "C-5"
        - "F-4"
        - "F-5"
        editor_partial: subfield_select
    - - n
      - values: 
        - "xF"
        - "xFC"
        - "xFCG"
        - "xFCGD"
        - "xFCGDA"
        - "xFCGDAE"
        - "xFCGDAEB"
        - "bB"
        - "bBE"
        - "bBEA"
        - "bBEAD"
        - "bBEADG"
        - "bBEADGC"
        - "bBEADGCF"
        editor_partial: subfield_autocomplete
    - - s
#      - validate: 
#        - msg: the field can contain 't', '+' or '?'
#          value: "'^[t\\+\\?][t\\+\\?]?[t\\+\\?]?$'"
#          rule: regex
    - - p
      - editor_partial: subfield_pae
    - - q

"033": 
  layout: 
    fields: 
    - - indicator
      - editor_partial: subfield_indicator
    - - a
"040": 
  layout: 
    fields:
    - - a
      - hidden: true
    - - d
      - hidden: true 
    - - b
      - values: 
        - "eng"
        - "fre"
        - "ger"
        - "grc"
        - "gsw"
        - "ita"
        - "lat"
        - "roh"
        - "rus"
        - "spa"
        editor_partial: subfield_autocomplete
"041": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
    - - e
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
    - - h
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
    columns: 2
  tag_params:
    codes:
      - "cat"
      - "cze"
      - "dan"
      - "dut"
      - "eng"
      - "fre"
      - "ger"
      - "grc"
      - "gre" 
      - "gsw"
      - "heb"
      - "hrv"
      - "hun"
      - "ita"
      - "kor"
      - "lat"
      - "pol"
      - "por"
      - "roh"
      - "rus"
      - "slo"
      - "slv"
      - "spa"
      - "srp"
      - "swe"
      - "zxx"
"100": 
  new_window: people
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - cols: 2
        editor_partial: subfield_select_codes
        select_label: "Attribution"
    columns: 2
  tag_params:
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
      - "Verified"
"240": 
  new_window: standard_titles
  layout: 
    fields: 
    - - a
      - type: standard_title
        editor_partial: subfield_secondary
        allow_new: true
    - - k
    - - o
    - - r
    - - m
"245": 
  layout: 
    fields: 
    - - a
      - growfield: true
"260": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
    - - e
    - - f
"300": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - c
"340": 
  layout: 
    fields: 
    - - a
"383": 
  layout: 
    fields: 
    - - b
"500": 
  layout: 
    fields: 
    - - a
      - growfield: true
"508": 
  layout: 
    fields: 
    - - a
      - values: 
        - "Arranger: "
        - "Artist: "
        - "Associated name: "
        - "Binder: "
        - "Bookseller: "
        - "Conceptor: "
        - "Choreographer: "
        - "Collaborator: "
        - "Composer: "
        - "Compiler: "
        - "Conductor: "
        - "Censor: "
        - "Costume designer: "
        - "Dancer: "
        - "Donor: "
        - "Dedicatee: "
        - "Dubious author: "
        - "Editor: "
        - "Engraver: "
        - "Former owner: "
        - "Illustrator: "
        - "Instrumentalist: "
        - "Librettist: "
        - "Lithograph: "
        - "Lyricist: "
        - "Patron: "
        - "Paper maker: "
        - "Production personnel: "
        - "Performer: "
        - "Printer: "
        - "Scribe: "
        - "Translater: "
        - "Vocalist: "
        growfield: true
        editor_partial: subfield_autocomplete
"518": 
  layout: 
    fields: 
    - - a
      - values: 
        - "Composition date: "
        - "First performance date: "
        - "Performance date: "
        editor_partial: subfield_autocomplete
"541": 
  layout: 
    fields: 
    - - c
      - growfield: true
    - - a
    - - d
    - - e
"590": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - b
      - growfield: true
"592": 
  layout: 
    fields: 
    - - a
"593": 
  layout: 
    fields: 
    - - a
      - values: 
        - Autograph
        - Manuscript
        - Manuscript with autograph annotations
        - Partly Autograph
        - Print
        - Print with handwritten entries
        - Probably autograph
        editor_partial: subfield_select
"594":
  layout: 
    fields: 
    - - b
      - type: source_594b_solr
        field: value
        editor_partial: subfield_secondary
        allow_new: true
    - - c
"597": 
  layout: 
    fields: 
    - - a
"598": 
  layout: 
    fields: 
    - - a
#      - validate: 
#        - msg: this field must be 4 characters
#          value: "'^[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]$'"
#          rule: regex
    - - b
    - - c
#      - validate: 
#        - msg: this field must be 4 characters
#          value: "'^[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]$'"
#          rule: regex
    - - d
    - - e
    - - f
#      - validate: 
#        - msg: this field must be 5 characters
#          value: "'^[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]$'"
#          rule: regex
    - - g
#      - validate: 
#        - msg: this field must be 4 characters
#          value: "'^[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]$'"
#          rule: regex
    - - h
#      - validate: 
#        - msg: this field must be 3 characters
#          value: "'^[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]$'"
#          rule: regex
    - - i
    - - k
    - - l
    - - m
    - - n
"650":
  new_window: standard_terms
  layout: 
    fields: 
    - - a
      - type: standard_term
        editor_partial: subfield_secondary
        allow_new: true
"651":
  new_window: places
  layout: 
    fields: 
    - - a
      - type: place
        editor_partial: subfield_secondary
        allow_new: true
"657": 
  new_window: liturgical_feasts
  layout: 
    fields: 
    - - a
      - type: liturgical_feast
        editor_partial: subfield_secondary
        allow_new: true
"690": 
  new_window: catalogues
  layout: 
    fields: 
    - - a
      - type: catalogue
        editor_partial: subfield_secondary
        allow_new: true
    - - n
"691":
  new_window: catalogues
  layout: 
    fields: 
    - - a
      - type: catalogue
        editor_partial: subfield_secondary
        allow_new: true
    - - n
"700":
  new_window: people
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - editor_partial: subfield_select_codes
    - - "4"
      - editor_partial: subfield_relator_codes_700
  tag_list_additional_data: tag_list_additional_data_relator_codes
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
      - "Verified"
    groups: 
      01_codes_artistic: 
      - cmp
      - com
      - arr
      - aut
      - clb
      - lyr
      - ccp
      - lbt
      - trl
      02_codes_performing: 
      - prf
      - voc
      - itr
      - dnc
      - cnd
      - chr
      - art
      - cst
      - prd
      - cns
      04_codes_other: 
      - fmo
      - dnr
      - dte
      - pat
      - otm
      - bsl
      - asn
      - dub
      03_codes_technical: 
      - scr
      - ltg
      - egr
      - ill
      - prt
      - pbl
      - edt
      - bnd
"710":
  new_window: institutions
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
        allow_new: true
    - - b
    - - g
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
  tag_params: 
    codes: 
    - fmo
    - dnr
    - dte
    - prf
    - otm
    - ppm
    - prt
    - pbl
    - edt
    - bsl
    - asn
    - dub
    - evp
    - dpt
"730":
  new_window: standard_titles
  layout: 
    fields: 
    - - a
      - type: standard_title
        editor_partial: subfield_secondary
        allow_new: true
    - - g
      - values: 
        - "RISM"
        - "RDA"
        - "RAK"
        default: "RISM"
        editor_partial: subfield_select
    - - k
    - - o
    - - r
    - - n
    - - m
"740":
  layout: 
    fields: 
    - - a
      - type: source_solr
        field: value
        editor_partial: subfield_secondary
        allow_new: true
    - - n
    - - p
"772": 
  layout: 
    fields: 
    - - w
      - read_only: true
"773":
  new_window: sources
  layout: 
    fields: 
    - - w
      - type: source
        editor_partial: subfield_secondary
"775":
  new_window: sources
  layout: 
    fields: 
    - - w
      - type: source
        editor_partial: subfield_secondary
"787": 
  layout: 
    fields: 
    - - g
    - - n
    - - s
    - - w
"852": 
  new_window: institutions
  layout: 
    fields: 
    - - a
      - type: library
        editor_partial: subfield_secondary
        allow_new: true
    - - e
      - autocomplete_extra: name
    - - b
    - - z
    - - p
      - growfield: true
    - - d
ui: 
  hide_marc_identifiers: true
