--- !map:Settings 
group_order: 
- show_summary
- show_library
- show_content
- show_distribution
- show_material
- show_information
- show_references
- show_terms
- show_resources
- show_admin
- show_links

groups: 
  
  show_summary: 
    all_tags: 
    - "100"
    - "240"
    - "383"
    - "245"
    - "246"
    - "657"
    - "730"
    all_tag_templates: 
      "100": marc_show/show_person
      "246": marc_show/show_title_variant  

  show_library: 
    all_tags:
    - "852"
    - "591"
    - "506"
    - "035"
    - "541"
    - "001"
  
  show_content: 
    all_tags: 
    - "031"
    - "740"
    all_tag_templates: 
      "031": marc_show/show_incipit
  
  show_distribution: 
    all_tags: 
    - "653"
    - "594"
    - "598"

  show_material: 
    all_tags: 
    - "593"
    - "260"
    - "518"
    - "300"
    - "590"
    - "340"
    - "028"
    - "592"
    - "700"
    - "710"
    - "500"
    - "597"
    - "856"
    subfield_grouping: 8
    all_tag_templates: 
      "260": marc_show/show_subfield_concat
      "700": marc_show/show_person
      "710": marc_show/show_institution

  show_information: 
    all_tags: 
    - "500"
    - "511"
    - "518"
    - "520"
    - "525"
    - "546"
    - "561"
    ungrouped_tags:
      "500": 8
      "518": 8

  show_references: 
    all_tags: 
    - "596"
    - "690"
    - "383"
    - "691"
    all_tag_templates: 
      "690": marc_show/show_subfield_concat
      "691": marc_show/show_subfield_concat

  show_terms: 
    all_tags: 
    - "650"
    - "041"
    - "700"
    - "710"
    - "651"
    all_tag_templates: 
      "700": marc_show/show_person
      "710": marc_show/show_institution
      "752": marc_show/show_place
      "650": marc_show/show_subject
    ungrouped_tags:
      "700": 8
      "710": 8

  show_resources:
    all_tags:
    - "787"
    - "856"
    ungrouped_tags:
      "856": 8
  
  show_admin: 
    all_tags: 
    - "040"
    - "599"
    admin_only: true
    
  show_links: 
    all_tags: 
    - "772"
    - "773"
    template: marc_show/show_772_773_links
