--- !map:Settings
"031": 
  tags:
    a: required
    b: required
    c: required
    e:
      depends:
        "031": "m"
    n:
      depends:
        "031": "p"
    o:
      depends:
        "031": "p"
    r:
      depends:
        "031": "p"
"041": 
  tags:
    a:
      depends:
        "031": "t"