--- 
### Configuration for source
- :model: source
  :record_types:
    :unspecified: 0
    :collection: 1
    :manuscript: 2
    :print: 3
    :manuscript_libretto: 4
    :print_libretto: 5
    :theoretica: 6
    :convolutum: 7